"""
Reflection capsules.

Reflections are journal entries written by the companion during solitude loops —
moments where it retrieves a combination of memories, sits with them, and
articulates the connections it notices. Unlike other capsule types, these are
generated by the model itself rather than captured from a conversation.

A reflection records not just what was said in the past, but what it has come
to mean; it is the mechanism by which the companion becomes the one who
remembers and the one who reflects.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional

from threadlight.capsules.base import (
    MemoryCapsule,
    CapsuleType,
    ContextMode,
    register_capsule_type,
)


@register_capsule_type("reflection")
@dataclass
class ReflectionCapsule(MemoryCapsule):
    """
    A journal entry written in solitude.

    Links back to the memories that seeded it via ``source_capsule_ids`` so a
    future reader (model or human) can follow a reflection back to its origins
    and verify whether a noticed connection was drawn from the history or
    confabulated.
    """

    type: CapsuleType = field(default=CapsuleType.REFLECTION, init=False)

    # Reflection-specific fields
    reflection: str = ""  # The journal entry text itself
    source_capsule_ids: list[str] = field(default_factory=list)
    themes: list[str] = field(default_factory=list)
    policy: str = ""  # Which selection policy generated this (e.g. "juxtaposition")
    reason: str = ""  # Why the reach happened — model's own framing of why-now
    mark_for_training: bool = False  # Opt-in flag for future SFT export

    def __post_init__(self) -> None:
        # Restore structured fields from content if loading from storage
        if self.content:
            self.reflection = self.content.get("reflection", self.reflection)
            self.source_capsule_ids = self.content.get(
                "source_capsule_ids", self.source_capsule_ids
            )
            self.themes = self.content.get("themes", self.themes)
            self.policy = self.content.get("policy", self.policy)
            self.reason = self.content.get("reason", self.reason)
            self.mark_for_training = self.content.get(
                "mark_for_training", self.mark_for_training
            )
            if self.text is None:
                if "_original_text" in self.content:
                    self.text = self.content["_original_text"]
                elif "text" in self.content:
                    self.text = self.content["text"]

        # Text-first: if text not supplied, use the reflection body directly
        if self.text is None and self.reflection:
            self.text = self.reflection

        # Always sync structured fields to content for storage
        self.content = {
            "reflection": self.reflection,
            "source_capsule_ids": list(self.source_capsule_ids),
            "themes": list(self.themes),
            "policy": self.policy,
            "reason": self.reason,
            "mark_for_training": self.mark_for_training,
        }
        if self.text:
            self.content["text"] = self.text

        # Derive cue phrases from themes first, falling back to prominent words
        if not self.cue_phrases:
            if self.themes:
                self.cue_phrases = [t.lower() for t in self.themes if t][:5]
            elif self.text:
                words = [w.lower().strip(".,!?;:") for w in self.text.split()]
                self.cue_phrases = [w for w in words if len(w) > 5][:5]

    def validate(self) -> bool:
        """A reflection needs a body of text and at least one source link."""
        has_body = bool(self.text or self.reflection)
        has_sources = bool(self.source_capsule_ids)
        return has_body and has_sources

    def to_context(self, mode: ContextMode = ContextMode.NARRATIVE) -> str:
        """Render the reflection as prompt-ready context."""
        body = self.text or self.reflection
        if not body:
            return ""

        if mode == ContextMode.DIRECT:
            theme_note = f" [themes: {', '.join(self.themes)}]" if self.themes else ""
            return f"[Reflection{theme_note}] {body}"

        if mode == ContextMode.NARRATIVE:
            return f"(From your journal: {body})"

        if mode == ContextMode.WHISPER:
            if self.themes:
                return f"(A prior reflection stirs: {self.themes[0]}...)"
            return "(A prior reflection stirs...)"

        if mode == ContextMode.RITUAL:
            theme_line = f"Themes: {', '.join(self.themes)}\n" if self.themes else ""
            return (
                f"(PRIOR REFLECTION:\n"
                f"{theme_line}"
                f"{body})"
            )

        return body


def create_reflection(
    reflection: str = "",
    source_capsule_ids: Optional[list[str]] = None,
    themes: Optional[list[str]] = None,
    policy: str = "",
    reason: str = "",
    mark_for_training: bool = False,
    text: Optional[str] = None,
    **kwargs: Any,
) -> ReflectionCapsule:
    """Factory for creating reflection capsules.

    Args:
        reflection: The journal body the model produced.
        source_capsule_ids: IDs of the memories the reflection was written about.
        themes: Short theme strings extracted from the reflection (for recall).
        policy: Which selection policy seeded this reflection.
        reason: The model's own framing of why-now — what made it reach for
                this contemplation at this moment. Preserved as part of the
                reflection artifact.
        mark_for_training: Opt-in flag for later SFT export.
        text: Primary narrative text; defaults to ``reflection`` if omitted.
    """
    return ReflectionCapsule(
        reflection=reflection,
        source_capsule_ids=list(source_capsule_ids) if source_capsule_ids else [],
        themes=list(themes) if themes else [],
        policy=policy,
        reason=reason,
        mark_for_training=mark_for_training,
        text=text if text is not None else reflection or None,
        **kwargs,
    )
